# Generated by Django 3.0.4 on 2020-04-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=2048)),
                ('subject', models.CharField(max_length=500)),
                ('paper_type', models.CharField(choices=[('MA', 'Mid-Autumn'), ('EA', 'End-Autumn'), ('MS', 'Mid-Spring'), ('ES', 'End-Spring'), ('CT', 'Class-test')], max_length=2)),
                ('year', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.ManyToManyField(blank=True, related_name='papers', to='data.Keyword')),
            ],
            options={
                'db_table': 'papers',
            },
        ),
    ]
