# Generated by Django 3.0.4 on 2020-05-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.AlterField(
            model_name='paper',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Department'),
        ),
    ]
