# Generated by Django 3.0.4 on 2020-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200501_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
