# Generated by Django 3.0.4 on 2020-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200802_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('MA', 'Mid-Autumn'), ('EA', 'End-Autumn'), ('MS', 'Mid-Spring'), ('ES', 'End-Spring'), ('CT', 'Class-test')], max_length=30),
        ),
    ]
