# Generated by Django 3.0.4 on 2020-05-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2048)),
                ('paper_type', models.CharField(choices=[('MA', 'Mid-Autumn'), ('EA', 'End-Autumn'), ('MS', 'Mid-Spring'), ('ES', 'End-Spring'), ('CT', 'Class-test')], max_length=2)),
                ('year', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'paper_requests',
            },
        ),
    ]
